In [183]:
%reload_ext autoreload 
%autoreload 2

import numpy as np
from enum import Enum, auto
from maps import default_map
from gymnasium.spaces import *
from gymnasium import Env 
from riskenv import RiskEnv

from riskstate import (AttackRes, Move, RiskState, SetupPhase, 
                       RecruitmentPhase, FirstFromAttackPhase, FirstToAttackPhase, ContinueAttackPhase, 
                       ReinforcePhase, SubsequentAttackPhase, FortifyPhase1, FortifyPhase2, 
                       FortifyPhase3, new_game)

Env = RiskEnv(2)
Env.risk 


In [184]:
Env.reset()
for i in range(42): 
    Env.step(i)

Env.get_observation()
Env.risk 

In [185]:
for i in range(7):
    Env.step(0)
Env.get_observation()
Env.risk

In [186]:
Env.step(0)
Env.step(1)
print(Env.risk)
Env.get_observation()


{'Phase': 5,
 'Territory': array([[5, 0],
        [3, 0],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1]])}

In [187]:
Env.step(0)
print(Env.get_observation())
Env.risk

{'Phase': 6, 'Territory': array([[5, 0],
       [3, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1]])}


In [188]:
Env.risk.action_space()

[3]

In [189]:
Env.step(3)
print(Env.risk)
Env.get_observation()

{'Phase': 4,
 'Territory': array([[5, 0],
        [2, 0],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1]])}

In [198]:

#Env.risk.step(1)
#Env.step(0)
Env.risk

In [200]:
Env.risk.action_space()

array([ 0,  1,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32, 34, 36, 38, 40])

In [201]:
Env.step(0)

({'Phase': 8,
  'Territory': array([[5, 0],
         [2, 0],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1],
         [1, 0],
         [1, 1]])},
 -1,
 False,
 {})

In [203]:
Env.risk.action_space()

array([ 0,  1,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32, 34, 36, 38, 40])

In [182]:
Env.reset()
import random

for i in range(41):
    Env.step(i)
for _ in range(100000):
    Env.step( random.choice(Env.risk.action_space()) )

    if _ % 10000 == 1:
        print(Env.get_short_observation())

Env.get_observation()

({'player_0': 21, 'player_1': 21}, 42)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)
({'player_0': 21, 'player_1': 21}, 43)


{'Phase': 2,
 'Territory': array([[1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [2, 0],
        [1, 1],
        [2, 0],
        [1, 1]])}

In [169]:
Env.reset()
from riskstate import SetupPhase

t = SetupPhase(0, 0, [0, 1], Env.risk.territories, len(Env.risk.territories))
t.action_space()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [7]:
Env.reset()
for i in range(42):
    Env.step(i)

Env.risk.territories


array([[1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 0],
       [1, 1],
       [1, 2]])

In [52]:
Env.get_observation()

{'Phase': 1,
 'Territory': array([[1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1],
        [1, 0],
        [1, 1]])}

In [54]:
(Env.risk.territories[:, 1] == Env.risk.current_player).nonzero()[0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])